import { useMemo } from 'react';
import { useParams } from 'react-router-dom';
import { useApiQuery } from '@/hooks/useApi';
import { useListParams } from '@/hooks/useListParams';
import { useSchool } from '@/layouts/SchoolContext';
import {
  Badge, Banner, Button, Card, Chart, DataTable, Empty, ErrorState, Grid, Kpi, Page, PageHead,
  PageSkeleton, Pagination, SearchInput, TextField, charts,
} from '@/components/ui';
import { useCsvDownload } from '@/pages/intelligence/shared';
import { fmt, todayKey } from '@/lib/format';
import { cellText, chartRows, tileValue } from './shared';
import type { ReportCatalogItem, ReportPreview } from './types';

/**
 * One report, on screen. The preview is generated by the same definition that
 * produces the CSV, so the export always matches what was reviewed here.
 */
export default function ReportViewerPage() {
  const { key = '' } = useParams();
  const { campusParam, campus, scope } = useSchool();
  const list = useListParams({ sort: '', pageSize: 25 }, ['date', 'from', 'to']);
  const { download, busy } = useCsvDownload();

  const catalog = useApiQuery<ReportCatalogItem[]>('/reports/catalog');
  const def = catalog.data?.find((r) => r.key === key);
  const filters = def?.filters ?? [];

  const rangeError = list.filters.from && list.filters.to && list.filters.from > list.filters.to
    ? 'The start date must be before the end date'
    : undefined;

  // The filters the report actually reads — anything else would only confuse the URL.
  const reportParams = useMemo(() => ({
    ...campusParam,
    ...(filters.includes('date') ? { date: list.filters.date || undefined } : {}),
    ...(filters.includes('range') && !rangeError
      ? { from: list.filters.from || undefined, to: list.filters.to || undefined }
      : {}),
  }), [campusParam, filters, list.filters.date, list.filters.from, list.filters.to, rangeError]);

  const q = useApiQuery<ReportPreview>(`/reports/${key}/preview`, {
    ...reportParams,
    q: list.q || undefined,
    page: list.page,
    pageSize: list.pageSize,
    sort: list.sort.key || undefined,
    dir: list.sort.dir,
  }, { enabled: !!def });

  const head = (
    <PageHead
      crumbs={[{ label: 'Report Centre', to: '/admin/reports' }, { label: def?.title ?? 'Report' }]}
      title={q.data?.title ?? def?.title ?? 'Report'}
      sub={q.data?.description ?? def?.description}
      actions={
        <Button
          variant="primary"
          icon="download"
          loading={busy === key}
          disabled={!q.data || !q.data.matchedRows}
          onClick={() => download(key, `/reports/${key}/export`, reportParams, `${key}.csv`)}
        >
          Export CSV
        </Button>
      }
    />
  );

  if (catalog.isLoading || (q.isLoading && !q.data)) return <Page>{head}<PageSkeleton kpis={4} /></Page>;
  if (catalog.error) return <Page>{head}<ErrorState error={catalog.error} onRetry={() => catalog.refetch()} /></Page>;
  if (!def) {
    return (
      <Page>
        {head}
        <Empty
          icon="lock"
          title="That report is not available to you"
          sub="It may have been renamed, or it may be reserved for another role."
          action={<Button to="/admin/reports" icon="chevronLeft">Back to Report Centre</Button>}
        />
      </Page>
    );
  }
  if (q.error || !q.data) return <Page>{head}<ErrorState error={q.error} onRetry={() => q.refetch()} /></Page>;

  const p = q.data;
  const bars = chartRows(p);
  const meta = {
    page: list.page,
    pageSize: list.pageSize,
    total: p.matchedRows,
    totalPages: Math.max(1, Math.ceil(p.matchedRows / list.pageSize)),
  };

  return (
    <Page>
      {head}

      <div className="filterbar">
        <Badge tone="neutral" icon="building">
          {scope === 'group' ? 'All campuses' : campus?.name ?? 'All campuses'}
        </Badge>
        {filters.includes('date') && (
          <TextField
            label="As at date"
            type="date"
            max={todayKey()}
            value={list.filters.date}
            onChange={(v) => list.setFilter('date', v)}
          />
        )}
        {filters.includes('range') && (
          <>
            <TextField label="From" type="date" max={todayKey()} value={list.filters.from} onChange={(v) => list.setFilter('from', v)} />
            <TextField label="To" type="date" max={todayKey()} value={list.filters.to} onChange={(v) => list.setFilter('to', v)} error={rangeError} />
          </>
        )}
        <SearchInput value={list.q} onSearch={list.setQ} placeholder="Search this report" />
        {list.hasFilters && <Button size="sm" variant="quiet" onClick={list.clear}>Clear</Button>}
        <div className="spacer" />
        <span className="t-xs t-muted">Generated {fmt.date(p.generatedAt)} · exports are audited</span>
      </div>

      <Grid cols="g-4col" className="mt-4">
        <Kpi
          label={list.q ? 'Matching rows' : 'Rows'}
          value={fmt.n(p.matchedRows)}
          foot={list.q && p.matchedRows !== p.totalRows ? `of ${fmt.n(p.totalRows)} total` : undefined}
        />
        {p.summary.map((s) => (
          <Kpi key={s.label} label={s.label} value={tileValue(s)} tone={s.tone} />
        ))}
      </Grid>

      {p.truncated && (
        <div className="mt-4">
          <Banner tone="warning" icon="alertCircle">
            This report returned more than 20,000 rows. The figures above cover everything, but export the CSV to work with the full detail.
          </Banner>
        </div>
      )}

      {bars.length > 0 && (
        <Card className="mt-4" title={p.chart!.label} sub={bars.length === 12 ? 'Top 12 by value' : undefined}>
          <Chart svg={charts.hbar({ rows: bars, labelW: 160, label: p.chart!.label })} />
        </Card>
      )}

      <Card className="mt-4" title="Report data" sub={`${fmt.n(p.matchedRows)} row${p.matchedRows === 1 ? '' : 's'} · ${p.columns.length} columns`} flush>
        <DataTable
          rows={p.rows}
          loading={q.isFetching}
          rowKey={(r) => String(r.__row)}
          sort={list.sort}
          onSort={list.setSort}
          emptyText={list.q ? 'No rows match that search.' : 'This report has no rows for the selected filters.'}
          columns={p.columns.map((c) => ({
            key: c.key,
            label: c.label,
            className: p.numeric.includes(c.key) ? 'num' : undefined,
            render: (row: Record<string, unknown>) => {
              const text = cellText(row[c.key], c, p.numeric);
              if (text === null) return <span className="t-faint">—</span>;
              return p.numeric.includes(c.key) ? <span className="t-num">{text}</span> : text;
            },
          }))}
        />
        <Pagination meta={meta} onPage={list.setPage} onPageSize={list.setPageSize} />
      </Card>
    </Page>
  );
}
